config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'landing/index'
  root :to => 'landing#index'

  match 'volume/:id', to: 'volumes#assign_to_user',  via: [:post], as: 'assign_volume_to_user'
  match 'volume/:id', to: 'volumes#disconnect_from_user',  via: [:delete], as: 'disconnect_volume_from_user'

  get 'list/:id', to: 'list#list',  via: [:get], as: 'list'

  resources :series, :authors, :volumes
  namespace :admin do
    resources :authors, :volumes, :series
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/volume.rb
class Volume < ApplicationRecord
  belongs_to :series
  has_and_belongs_to_many :authors
  has_and_belongs_to_many :users
end

app/controllers/admin/volumes_controller.rb
class Admin::VolumesController < AdminController
  before_action :set_volume, only: [:show, :edit, :update, :destroy]
  before_action :set_form_relations, only: [:new, :edit, :create]

  # GET /volumes
  # GET /volumes.json
  def index
    @volumes = Volume.all
  end

  # GET /volumes/1
  # GET /volumes/1.json
  def show
  end

  # GET /volumes/new
  def new
    @volume = Volume.new
  end

  # GET /volumes/1/edit
  def edit
  end

  # POST /volumes
  # POST /volumes.json
  def create
    @volume = Volume.new(volume_params)

    respond_to do |format|
      if @volume.save
        format.html { redirect_to @volume, notice: 'Volume was successfully created.' }
        format.json { render :show, status: :created, location: @volume }
      else
        format.html { render :new }
        format.json { render json: @volume.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /volumes/1
  # PATCH/PUT /volumes/1.json
  def update
    respond_to do |format|
      if @volume.update(volume_params)
        format.html { redirect_to @volume, notice: 'Volume was successfully updated.' }
        format.json { render :show, status: :ok, location: @volume }
      else
        format.html { render :edit }
        format.json { render json: @volume.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /volumes/1
  # DELETE /volumes/1.json
  def destroy
    @volume.destroy
    respond_to do |format|
      format.html { redirect_to admin_volumes_url, notice: 'Volume was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_volume
      @volume = Volume.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def volume_params
      params.fetch(:volume, {})
    end

    def set_form_relations
      @series = Series.all
      @authors = Author.all
    end
end

app/controllers/volumes_controller.rb
class VolumesController < ApplicationController
  before_action :set_volume, only: [:show, :edit, :update, :destroy, :assign_to_user, :disconnect_from_user]


  # GET /volumes
  # GET /volumes.json
  def index
    @volumes = Volume.all
  end

  # GET /volumes/1
  # GET /volumes/1.json
  def show
  end

  def assign_to_user
    VolumeService::VolumeToUserAssign.new(current_user, @volume).exec
    respond_to do |format|
      if @volume.save
        format.html { redirect_to @volume, notice: 'Volume was successfully assign.' }
        format.json { render :show, status: :created, location: @volume }
      else
        format.html { render :new }
        format.json { render json: @volume.errors, status: :unprocessable_entity }
      end
    end
  end

  def disconnect_from_user
    VolumeService::VolumeFromUserDisconnect.new(current_user, @volume).exec
    respond_to do |format|
      if @volume.save
        format.html { redirect_to @volume, notice: 'Volume was successfully disconnected.' }
        format.json { render :show, status: :created, location: @volume }
      else
        format.html { render :new }
        format.json { render json: @volume.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_volume
      @volume = Volume.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def volume_params
      params.require(:volume).permit(:title, :description, {author_ids: [:id]}, :series_id)
    end

    def set_form_relations
      @series = Series.all
      @authors = Author.all
    end
end

app/helpers/admin/volumes_helper.rb
module Admin::VolumesHelper
end

app/helpers/volumes_helper.rb
module VolumesHelper
end

app/views/volumes/_form.html.erb
<%= form_with(model: volume, local: true) do |form| %>
  <% if volume.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(volume.errors.count, "error") %> prohibited this volume from being saved:</h2>

      <ul>
      <% volume.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= collection_select(:volume, :author_ids, @authors, :id, :full_name, {}, {:multiple => true}) %>
  </div>

  <div class="field">
    <%= collection_select(:volume, :series_id, @series, :id, :name) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/volumes/edit.html.erb
<h1>Editing Volume</h1>

<%= render 'form', volume: @volume %>

<%= link_to 'Show', @volume %> |
<%= link_to 'Back', volumes_path %>

app/views/volumes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Volumes</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @volumes.each do |volume| %>
      <tr>
        <td><%= volume.title %></td>
        <td><%= volume.description %></td>
        <td><%= link_to 'Show', volume %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Volume', new_volume_path %>

app/views/volumes/new.html.erb
<h1>New Volume</h1>

<%= render 'form', volume: @volume %>

<%= link_to 'Back', volumes_path %>

app/views/volumes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @volume.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @volume.description %>
</p>
<p>
  <strong>authors</strong>
  <% @volume.authors.each do |author| %>
    <%= author.full_name %>
  <% end %>
</p>


<% if user_signed_in? %>
  <% if @volume.users.include? current_user %>
      <%= link_to "Mark as unhave", disconnect_volume_from_user_path(@volume), method: :delete %>
    <% else %>
      <%= link_to "Mark as have", assign_volume_to_user_path(@volume), method: :post %>
    <% end %>
<% end %>

<%= link_to 'Back', volumes_path %>