config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'landing/index'
  root :to => 'landing#index'

  match 'volume/:id', to: 'volumes#assign_to_user',  via: [:post], as: 'assign_volume_to_user'
  match 'volume/:id', to: 'volumes#disconnect_from_user',  via: [:delete], as: 'disconnect_volume_from_user'

  get 'list/:id', to: 'list#list',  via: [:get], as: 'list'

  resources :series, :authors, :volumes
  namespace :admin do
    resources :authors, :volumes, :series
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_and_belongs_to_many :volumes

  validates :first_name, presence: true,
            length: { minimum: 3 }
  validates :last_name, presence: true,
            length: { minimum: 3 }

  def full_name
    first_name + ' ' + last_name
  end
end

app/models/series.rb
class Series < ApplicationRecord
  has_many :volumes
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :trackable

  has_and_belongs_to_many :volumes

  validates :nickname,  length: { in: 3..25 }
end

app/models/volume.rb
class Volume < ApplicationRecord
  belongs_to :series
  has_and_belongs_to_many :authors
  has_and_belongs_to_many :users
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_user!
  layout "admin_application"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
#  before_action :set_author, only: [:show, :edit, :update, :destroy]
#  before_action :authenticate_user!, only: [:edit, :update, :create, :new]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:first_name, :last_name, :description)
    end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
  end
end

app/controllers/list_controller.rb
class ListController < ApplicationController

  def list
    @volumes = VolumeService::GetAllForUser.new(user_params).exec
  end

private

  def user_params
    params[:id]
  end
end

app/controllers/series_controller.rb
class SeriesController < ApplicationController
  before_action :set_series, only: [:show, :edit, :update, :destroy]

  # GET /series
  # GET /series.json
  def index
    @series = Series.all
  end

  # GET /series/1
  # GET /series/1.json
  def show
  end

  # GET /series/new
  def new
    @series = Series.new
  end

  # GET /series/1/edit
  def edit
  end

  # POST /series
  # POST /series.json
  def create
    @series = Series.new(series_params)

    respond_to do |format|
      if @series.save
        format.html { redirect_to @series, notice: 'Series was successfully created.' }
        format.json { render :show, status: :created, location: @series }
      else
        format.html { render :new }
        format.json { render json: @series.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /series/1
  # PATCH/PUT /series/1.json
  def update
    respond_to do |format|
      if @series.update(series_params)
        format.html { redirect_to @series, notice: 'Series was successfully updated.' }
        format.json { render :show, status: :ok, location: @series }
      else
        format.html { render :edit }
        format.json { render json: @series.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /series/1
  # DELETE /series/1.json
  def destroy
    @series.destroy
    respond_to do |format|
      format.html { redirect_to series_index_url, notice: 'Series was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_series
      @series = Series.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def series_params
      params.require(:series).permit(:name)
    end
end

app/controllers/volumes_controller.rb
class VolumesController < ApplicationController
  before_action :set_volume, only: [:show, :edit, :update, :destroy, :assign_to_user, :disconnect_from_user]


  # GET /volumes
  # GET /volumes.json
  def index
    @volumes = Volume.all
  end

  # GET /volumes/1
  # GET /volumes/1.json
  def show
  end

  def assign_to_user
    VolumeService::VolumeToUserAssign.new(current_user, @volume).exec
    respond_to do |format|
      if @volume.save
        format.html { redirect_to @volume, notice: 'Volume was successfully assign.' }
        format.json { render :show, status: :created, location: @volume }
      else
        format.html { render :new }
        format.json { render json: @volume.errors, status: :unprocessable_entity }
      end
    end
  end

  def disconnect_from_user
    VolumeService::VolumeFromUserDisconnect.new(current_user, @volume).exec
    respond_to do |format|
      if @volume.save
        format.html { redirect_to @volume, notice: 'Volume was successfully disconnected.' }
        format.json { render :show, status: :created, location: @volume }
      else
        format.html { render :new }
        format.json { render json: @volume.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_volume
      @volume = Volume.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def volume_params
      params.require(:volume).permit(:title, :description, {author_ids: [:id]}, :series_id)
    end

    def set_form_relations
      @series = Series.all
      @authors = Author.all
    end
end

app/helpers/admin/authors_helper.rb
module Admin::AuthorsHelper
end

app/helpers/admin/series_helper.rb
module Admin::SeriesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/helpers/series_helper.rb
module SeriesHelper
end

app/helpers/volumes_helper.rb
module VolumesHelper
end

app/views/layouts/admin_application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Admin</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
  <nav class="navbar navbar-dark navbar-expand-lg" style="background-color: #282828;">
    <a class="navbar-brand" href="#">Collection</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="true" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <%= link_to 'Volumes', admin_volumes_path, class: 'nav-item nav-link' %>
        <%= link_to 'Authors', admin_authors_path, class: 'nav-item nav-link'%>
        <%= link_to 'Series', admin_series_index_path, class: 'nav-item nav-link' %>
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Hello,<%= current_user.nickname %> </a>
            <div class="dropdown-menu">
              <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: 'nav-item nav-link' %>
              <%= link_to 'My List', list_path(:id => current_user) , class: 'nav-item nav-link' %>
              <a class="dropdown-item" href="#">Something else here</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Separated link</a>
            </div>
          </li>

        <% else %>
         <%= link_to 'Log in', user_session_path, class: 'nav-item nav-link'%>
         <%= link_to 'Create account', new_user_registration_path, class: 'nav-item nav-link'  %>
        <% end %>

      </div>
    </div>
  </nav>

    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Collection2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
  <nav class="navbar navbar-light navbar-expand-lg" style="background-color: #e3f2fd;">
    <a class="navbar-brand" href="#">Collection</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="true" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <%= link_to 'Volumes', volumes_path, class: 'nav-item nav-link' %>
        <%= link_to 'Authors', authors_path, class: 'nav-item nav-link'%>
        <%= link_to 'Series', series_index_path, class: 'nav-item nav-link' %>
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Hello,<%= current_user.nickname %> </a>
            <div class="dropdown-menu">
              <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: 'nav-item nav-link' %>
              <%= link_to 'My List', list_path(:id => current_user) , class: 'nav-item nav-link' %>
              <% %>
              <a class="dropdown-item" href="#">Something else here</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Separated link</a>
            </div>
          </li>

        <% else %>
         <%= link_to 'Log in', user_session_path, class: 'nav-item nav-link'%>
         <%= link_to 'Create account', new_user_registration_path, class: 'nav-item nav-link'  %>
        <% end %>

      </div>
    </div>
  </nav>

    <%= yield %>
  </body>
</html>